spring.datasource.url: jdbc:mysql://localhost:3306/search_engine
spring.datasource.username: root
spring.datasource.password: enteryourpassword
spring.jpa.hibernate.dll-auto: create
spring.jpa.hibernate.use-new-id-generator-mappings: false
sites:
  urls:
    - http://playback.ru/
    - http://playback.ru/
